Issue 65 completed
OnionIoT/documentation pull request #87
Opened 2024-05-08 18:40 UTC by remingtontr

Article rewritten and link to doc in sidebar removed. The DocCardList will now display all three docs in the parent folder.

2024-05-09 18:29 UTC, greenbreakfast requested changes
Looking good, just have a few wording fixes

2024-05-09 18:29 UTC, greenbreakfast commented on docs/device-tree-overlay/intro.md
> +## How a Device Tree is implemented
Should be "How a Device Tree Overlay is Implemented"

2024-05-09 18:29 UTC, greenbreakfast commented on docs/device-tree-overlay/intro.md
> +By default, OpenWRT supports static Device Trees in the form of Device Tree Specification (DTS) files. For example, all the DTS files for ramips-based devices can be found on [GitHub's OpenWRT](https
For the link, it would make more sense to say "OpenWRT's build system GitHub repo" instead of "GitHub's OpenWRT"

2024-05-09 18:29 UTC, greenbreakfast commented on docs/device-tree-overlay/intro.md
> +## How a Device Tree works on the device
Should be "How a Device Tree Overlay Package works on the device"

2024-05-09 18:59 UTC, remingtontr commented
Fixed and pushed.

Tom Remington
________________________________
From: Lazar ***@***.***>
Sent: May 9, 2024 11:29 AM
To: OnionIoT/documentation ***@***.***>
Cc: remingtontr ***@***.***>; Author ***@***.***>
Subject: Re: [OnionIoT/documentation] Issue 65 completed (PR #87)


@greenbreakfast requested changes on this pull request.

Looking good, just have a few wording fixes

________________________________

In docs/device-tree-overlay/intro.md<https://github.com/OnionIoT/documentation/pull/87#discussion_r1595824526>:

>
+## How a Device Tree is implemented


Should be "How a Device Tree Overlay is Implemented"

________________________________

In docs/device-tree-overlay/intro.md<https://github.com/OnionIoT/documentation/pull/87#discussion_r1595825404>:

>
 ### Device Trees in OpenWRT
+By default, OpenWRT supports static Device Trees in the form of Device Tree Specification (DTS) files. For example, all the DTS files for ramips-based devices can be found on [GitHub's OpenWRT](https://github.com/openwrt/openwrt/tree/main/target/linux/ramips/dts) repository.


For the link, it would make more sense to say "OpenWRT's build system GitHub repo" instead of "GitHub's OpenWRT"

________________________________

In docs/device-tree-overlay/intro.md<https://github.com/OnionIoT/documentation/pull/87#discussion_r1595826421>:

>
 :::

-## How to create custom Device Tree Overlay Packages
+## How a Device Tree works on the device


Should be "How a Device Tree Overlay Package works on the device"

—
Reply to this email directly, view it on GitHub<https://github.com/OnionIoT/documentation/pull/87#pullrequestreview-2048568415>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A4B4PDOMIED4KGTGDEGOVETZBO6AHAVCNFSM6AAAAABHNPTX62VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANBYGU3DQNBRGU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-05-10 17:45 UTC, merged

2024-05-10 17:45 UTC, greenbreakfast commented
looks good, thanks!
cc #65